# Generated by Django 4.1.6 on 2023-02-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
